name: Sanity Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout private environment
      uses: actions/checkout@v2
      with: 
        repository: wbh123456/RingBell_environment
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        path: env
    - name: Combine two repos
      run: |
        mv env/environment.py environment.py

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datetime
        pip install selenium
        pip install xlrd
        pip install xlutils
    - name: Test with example forms
      run: |
        python main.py --use_example --disable_email_sending
    - name: Run with email sending disabled
      run: |
        python main.py --disable_email_sending
